import { Bot, InlineKeyboard, type Context } from 'grammy';
import { services, masters, book, myBookings, cancel, slotsFor, nowLocal, addDays, hhmm } from './db-neon.ts';
const token=process.env.BOT_TOKEN??''; if(!token) throw new Error('BOT_TOKEN is not set');
const webAppUrl=process.env.WEB_APP_URL || process.env.RENDER_EXTERNAL_URL;
const bot=new Bot(token); const rub=(n:number)=>`${n.toLocaleString('ru-RU')} ₽`;
const dayLabel=(d:string)=>new Date(d+'T00:00:00Z').toLocaleDateString('ru-RU',{weekday:'short',day:'2-digit',month:'2-digit',timeZone:'UTC'});
const show=(ctx:Context,text:string,kb:InlineKeyboard)=>ctx.callbackQuery?ctx.editMessageText(text,{reply_markup:kb}).catch(()=>{}):ctx.reply(text,{reply_markup:kb});
const menu=()=>{const k=new InlineKeyboard(); if(webAppUrl)k.webApp('📱 Открыть приложение',webAppUrl).row(); return k.text('✂️ Записаться','book').row().text('💈 Услуги и цены','prices').row().text('📅 Мои записи','my');};
const home=(ctx:Context)=>show(ctx,'💈 BARBER HOUSE\nЗапишитесь на стрижку за минуту.',menu());
function showServices(ctx:Context){return services().then(ss=>{const kb=new InlineKeyboard();for(const s of ss as any[])kb.text(`${s.name} — ${rub(s.price)} · ${s.duration} мин`,`s:${s.id}`).row();return show(ctx,'Выберите услугу:',kb.text('« Назад','menu'));});}
function showMy(ctx:Context){return myBookings(ctx.from!.id).then(rows=>{const kb=new InlineKeyboard();for(const b of rows as any[])kb.text(`❌ ${dayLabel(b.date)} ${hhmm(b.start_min)}`,`c:${b.id}`).row();const text=rows.length?'Ваши записи (нажмите, чтобы отменить):\n\n'+rows.map((b:any)=>`• ${dayLabel(b.date)} ${hhmm(b.start_min)} — ${b.service_name}, ${b.master}`).join('\n'):'У вас пока нет предстоящих записей.';return show(ctx,text,kb.text('✂️ Записаться','book').row().text('« Назад','menu'));});}
bot.command(['start','help'],home); bot.command('book',showServices); bot.command('appointments',showMy);
bot.on('callback_query:data',async ctx=>{await ctx.answerCallbackQuery().catch(()=>{});const [k,...a]=ctx.callbackQuery.data.split(':');const ss=await services();const svc=(id:string)=>(ss as any[]).find(s=>s.id===+id);if(k==='menu')return home(ctx);if(k==='prices'){return show(ctx,(ss as any[]).map(s=>`• ${s.name} — ${rub(s.price)} (${s.duration} мин)`).join('\n'),new InlineKeyboard().text('✂️ Записаться','book').row().text('« Назад','menu'));}if(k==='book')return showServices(ctx);if(k==='my')return showMy(ctx);if(k==='c'){const ok=await cancel(+a[0],ctx.from!.id);return showMy(ctx);}if(k==='s'){const kb=new InlineKeyboard().text('Любой свободный',`m:${a[0]}:0`).row();for(const m of await masters() as any[])kb.text(m.name,`m:${a[0]}:${m.id}`).row();return show(ctx,`${svc(a[0])?.name}\nВыберите мастера:`,kb.text('« Назад','book'));}if(k==='m'){const [sid,mid]=a,s=svc(sid),kb=new InlineKeyboard(),today=nowLocal().date;let n=0;for(let i=0;i<14&&n<7;i++){const d=addDays(today,i);if(!(await slotsFor(+mid,d,s.duration)).length)continue;kb.text(dayLabel(d),`d:${sid}:${mid}:${d}`);if(++n%2===0)kb.row();}return show(ctx,n?'Выберите дату:':'Свободного времени на ближайшие две недели нет.',kb.row().text('« Назад',`s:${sid}`));}if(k==='d'){const [sid,mid,date]=a,s=svc(sid),slots=await slotsFor(+mid,date,s.duration),kb=new InlineKeyboard();slots.forEach((t,i)=>{kb.text(hhmm(t),`t:${sid}:${mid}:${date}:${t}`);if((i+1)%4===0)kb.row();});return show(ctx,slots.length?`${dayLabel(date)}\nВыберите время:`:'На эту дату времени не осталось.',kb.row().text('« Назад',`m:${sid}:${mid}`));}if(k==='t'){const [sid,mid,date,t]=a,s=svc(sid) as any;const mm=+mid?(await masters() as any[]).find(m=>m.id===+mid)?.name:'любой свободный мастер';return show(ctx,`Проверьте запись:\n\n${s.name} — ${rub(s.price)}\n${dayLabel(date)}, ${hhmm(+t)}\nМастер: ${mm}`,new InlineKeyboard().text('✅ Подтвердить',`ok:${sid}:${mid}:${date}:${t}`).row().text('« Назад',`d:${sid}:${mid}:${date}`));}if(k==='ok'){const [sid,mid,date,t]=a,s=svc(sid) as any,r=await book({tgId:ctx.from!.id,name:ctx.from!.first_name||'Клиент',masterId:+mid,serviceId:+sid,date,startMin:+t});if(!r)return show(ctx,'Это время только что заняли. Выберите другое.',new InlineKeyboard().text('Выбрать время',`d:${sid}:${mid}:${date}`));const m=(await masters() as any[]).find(x=>x.id===r.masterId)!.name;return show(ctx,`✅ Вы записаны!\n\n${r.service} — ${rub(r.price)}\n${dayLabel(date)}, ${hhmm(+t)}\nМастер: ${m}`,new InlineKeyboard().text('📅 Мои записи','my').row().text('« В меню','menu'));}});
bot.catch(e=>console.error('bot error',e.error));
export { bot };
